# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  appName: helloworld
  tfBackendStorageAccountName: $(appName)tfstatesa
  tfBackendStorageContainerName: tfstate
  tfBackendFileName: $(appName).tfstate

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
  displayName: 'Install Terraform 0.12.3'

- task: AzureKeyVault@1
  inputs:
    azureSubscription: $(appName)
    KeyVaultName: 'nexus-helloworld-kv'
  displayName: 'Get key vault secrets as pipeline variables'

- task: AzureCLI@1
  inputs:
    azureSubscription: $(appName)
    scriptLocation: 'inlineScript'
    inlineScript: 'terraform version'
  displayName: "Terraform Version"

- script: |
    cd $(System.DefaultWorkingDirectory)/tf-infra-provision

    echo '#######Initializing Credentials########'
    export ARM_CLIENT_ID=$(sp-ado-client-id) \
      ARM_CLIENT_SECRET=$(sp-ado-client-secret) \
      ARM_SUBSCRIPTION_ID=$(sp-ado-subscription-id) \
      ARM_TENANT_ID=$(sp-ado-tenant-id)
    
    echo '#######Terraform Init########'
    terraform init -backend-config="storage_account_name=$(tfBackendStorageAccountName)" -backend-config="container_name=$(tfBackendStorageContainerName)" -backend-config="access_key=$(sa-tfstate)" -backend-config="key=$(tfBackendFileName)"
    
    echo '#######Terraform Plan########'
    terraform plan -out="out.plan"
    
    echo '#######Terraform Apply########'
    terraform apply out.plan
  displayName: 'Terraform Init, Plan and Apply '